//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PePract5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkk
    {
        public int ID_Checkk { get; set; }
        public string Date_of_purchase { get; set; }
        public int Summ_Check { get; set; }
        public int Vneseno { get; set; }
        public Nullable<int> Sdacha { get; set; }
        public int EMP_ID { get; set; }
        public int Client_ID { get; set; }
        public int Korzina_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual EMP EMP { get; set; }
        public virtual Korzina Korzina { get; set; }
    }
}
