//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PePract5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdPractica5Entities : DbContext
    {
        public BdPractica5Entities()
            : base("name=BdPractica5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checkk> Checkk { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DanVxod> DanVxod { get; set; }
        public virtual DbSet<Dolz> Dolz { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<EMPDolz> EMPDolz { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Smena> Smena { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
    }
}
